version: "3.8"
services:
  backend-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "9090:9090"

  db:
    image: postgres:alpine
    container_name: socialite
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432" # Pastikan port ini sesuai dengan konfigurasi aplikasi Anda
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
